Change to use MQTT and Websockets
SolaceLabs/pcf-car-demo pull request #5
Opened 2017-11-01 08:34 UTC by schan-solace

2017-11-02 14:08 UTC, jschabowsky requested changes
In general looks really good, Just clean up lines which are commented out to make it cleaner if a client were to be reading through the code base.

2017-11-02 14:08 UTC, jschabowsky commented on cardemo/src/main/resources/static/js/build.js
> +        var hostname = "tcp.apps.pcfdemo.solacemessaging.net";
We really need to figure out a way to make this more portable such that we dont have to change the code each time the tcp routes change.

2017-11-02 14:08 UTC, jschabowsky commented on cardemo/src/main/resources/static/js/build.js
> +          //client.subscribe("World");
Delete these commented out lines

2017-11-02 14:08 UTC, jschabowsky commented on carmap/src/main/resources/static/TopicSubscriber.js
> +            var host = "tcp.apps.pcfdemo.solacemessaging.net:16322";
Same comment as above, need a better way to do this.

2017-11-02 14:08 UTC, jschabowsky commented on carmap/src/main/resources/static/TopicSubscriber.js
>          //setTimeout(function(){ marker.setAnimation(null); },100);
remove this line.

2017-11-06 06:18 UTC, schan-solace commented
Done.

Do I need to submit a new pull request, or is the existing one still active?

Steve

From: Jonathan Schabowsky <notifications@github.com>
Reply-To: SolaceLabs/pcf-car-demo <reply@reply.github.com>
Date: Thursday, 2 November 2017 at 10:08 PM
To: SolaceLabs/pcf-car-demo <pcf-car-demo@noreply.github.com>
Cc: Steve Chan <Steve.Chan@solace.com>, Author <author@noreply.github.com>
Subject: Re: [SolaceLabs/pcf-car-demo] Change to use MQTT and Websockets (#5)


@jschabowsky requested changes on this pull request.

In general looks really good, Just clean up lines which are commented out to make it cleaner if a client were to be reading through the code base.

________________________________

In cardemo/src/main/resources/static/js/build.js<https://github.com/SolaceLabs/pcf-car-demo/pull/5#discussion_r148541555>:

> @@ -236,7 +250,62 @@ var MyGame = {};

         this.helpButton.inputEnabled = true;

       }, this);



-      this.apiClient = new APIclient();

+      var carId = generateID();

+

+        var hostname = "tcp.apps.pcfdemo.solacemessaging.net";

We really need to figure out a way to make this more portable such that we dont have to change the code each time the tcp routes change.

________________________________

In cardemo/src/main/resources/static/js/build.js<https://github.com/SolaceLabs/pcf-car-demo/pull/5#discussion_r148541699>:

> +          onSuccess: onConnect,

+          onFailure: onFail

+        };

+

+        options.userName = userName;

+        options.password = passWord;

+

+        // connect the MQTT client

+        client.connect(options);

+        console.log('Connecting...');

+

+        // called when the client connects

+        function onConnect(context) {

+          // Once a connection has been made, make a subscription and send a message.

+          console.log("Connected");

+          //client.subscribe("World");

Delete these commented out lines

________________________________

In carmap/src/main/resources/static/TopicSubscriber.js<https://github.com/SolaceLabs/pcf-car-demo/pull/5#discussion_r148542021>:

>          if (subscriber.session !== null) {

             subscriber.log('Already connected and ready to subscribe.');

         } else {

             //var host = document.getElementById('host').value;

             //var vpn = document.getElementById('vpn').value;

             //var user = document.getElementById('user').value;

             //var pw = document.getElementById('password').value;

-            var host = "10.244.0.3:7000";

-            var vpn = "v003";

-            var user = "v003.cu000017";

-            var pw = "16698a80-0381-422d-a69e-aa6fb30eb273";

+            var host = "tcp.apps.pcfdemo.solacemessaging.net:16322";

Same comment as above, need a better way to do this.

________________________________

In carmap/src/main/resources/static/TopicSubscriber.js<https://github.com/SolaceLabs/pcf-car-demo/pull/5#discussion_r148542163>:

> @@ -210,6 +242,7 @@ var TopicSubscriber = function (topicName) {

         infoContent += '</p>';

         cars[id]["info"].setContent(infoContent);

         //setTimeout(function(){ marker.setAnimation(null); },100);

remove this line.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/SolaceLabs/pcf-car-demo/pull/5#pullrequestreview-73798343>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AXZKyhBUdtQ1-WEwncgSfKNpwKQdQU5Hks5syczTgaJpZM4QN5ME>.

2017-11-15 03:50 UTC, mdspielman commented
I have asked @jschabowsky for a final review.

2017-11-15 22:27 UTC, jschabowsky commented
Looks good to me. Lets merge as I will need this baseline for spring one as well!

2017-11-16 01:37 UTC, mdspielman commented
Thanks @jschabowsky. Merging.

2017-11-16 01:38 UTC, merged